### ISSUE TITLE
CI/CD Pipeline for the CMS

### ISSUE THREAD

**Issue by bemayr** [bemayr/young-carers-austria#22]
The CMS should be automatically built and deployed.

# Tasks
- [x] `Dockerfile` for Keystone.js
- [ ] SSH Deployment via `docker compose`
  - this could also be accomplished via: https://github.com/adnanh/webhook
  - even better it should be done with https://containrrr.dev/watchtower/http-api-mode/
- [ ] Environment Variable Handling + Documentation
- [ ] Push Dockerized CMS to Registry ([starter-workflow](https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml)]
- [ ] Delete unnecessarily created Workflows ([example bash script](https://gist.github.com/pckilgore/827bafd1bbda456b30ebd32ff652f9b6))
- [ ] Introduce proper Versioning
- [ ] Reduce Build Size
- [ ] Automatically Prune the Docker Images on the Production Server

# Resources
- [Keystone and Prisma's Database Migrations](https://github.com/keystonejs/keystone/discussions/7442)
- [Dockerizing a NestJS app with Prisma and PostgreSQL](https://notiz.dev/blog/dockerizing-nestjs-with-prisma-and-postgresql)
- [Prisma Migrate: Deploy Migration with Docker](https://notiz.dev/blog/prisma-migrate-deploy-with-docker)
- [next.js Example Dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker-multi-env/docker/production/Dockerfile)
- [Odi2357/cd-paper-gitflow-usecase1](https://github.com/Odi2357/cd-paper-gitflow-usecase1)

**Comment by bemayr** [comment]
Started working on this issue in #23

**Comment by bemayr** [comment]
Backlinked in #60.
