### ISSUE TITLE
Reduce CMS Docker Image Size

### ISSUE THREAD

**Issue by bemayr** [bemayr/young-carers-austria#25]
The currently built Docker Image is way too huge for a simple CMS system: [bemayr/young-carers-austria-cms:0.1.3](https://hub.docker.com/layers/bemayr/young-carers-austria-cms/0.1.3/images/sha256-21d01fc9bcc9bd893e8034765d6010c20fcb7cf1c7964cdf11f81ec0382fa66a?context=repo), the size is ~600MB.

# Possible Solutions
- [Dockerizing Next.js with Prisma for Production Environments](https://www.codemochi.com/blog/2022-01-01-dockerizing-nextjs-with-prisma-for-production)
  - 👎 Runs Prisma Commands at Build Time
- [Dockerize Next.js With Prisma App](https://javascript.plainenglish.io/dockerize-next-js-with-prisma-app-ff4ab5d79a31)
  - 👎 Runs Prisma Commands at Build Time
- [How did I reduce the docker image size by ~40% for a nextjs app?](https://akumbhani66.medium.com/how-did-i-reduce-the-docker-image-size-by-40-for-a-nextjs-app-d321b27e0dfc)
  - 👍 uses [tj/node-prune](https://github.com/tj/node-prune) to clean `node_modules`
    - [duniul/clean-modules](https://github.com/duniul/clean-modules) would be a modern alternative
- [NextJS Docker image is too big](https://github.com/vercel/next.js/discussions/31546)
  - 👎 only applies to Next.js
  - 👍 mentions Next.js' [standalone mode](https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files-experimental) (added in Next 12) as it is in [with-docker](https://github.com/vercel/next.js/blob/canary/examples/with-docker/README.md) example
- [**Production deployment exceeds 1G in dependencies**](https://github.com/keystonejs/keystone/issues/7286)
  - 👎 Issue is still open
  - 👍 This targets exactly Keystone.js

# Roadmap
- [x] multi stage docker builds
- [ ] clean node_modules
- [ ] utilize next.js standalone mode
- [ ] get rid of the `.next/cache` folder concerning webpack
- [ ] include only needed prisma providers

**Comment by bemayr** [comment]
Backlinked in #60.
