### ISSUE TITLE
Website Improvements

### ISSUE THREAD

**Issue by bemayr** [bemayr/young-carers-austria#54]
## TODOs:

- [x] Integrate Analytics
  - tracked in #35
- [x] Add Sitemap
  - https://github.com/matthiasott/eleventy-plus-vite/blob/main/src/sitemap.xml.njk
  - tracked by #110 
- [x] Create Mobile Menu (as full page popover)
  - https://twitter.com/nhoizey/status/1542833007119196160
  - https://larainfo.com/blogs/tailwind-css-sticky-header-fixed-navbar-example
- [x] #75
  - [x] add `showOnLandingPage` property so that the landing page does not get too full
  - [x] CSS-only tabs: https://codepen.io/MPDoctor/pen/mpJdYe
- [x] Integrate additional Data into CMS (for now in 11ty)
- [x] Create Alltagssituationen (content as component, so that it can be reused in Alltagssituationen)
- [x] Create Chatbot
  - tracked by #6
  - https://codepen.io/ScottWindon/pen/yLVgZjp
- [x] Create Infos properly
- [x] Mobile-First Styling
- [x] #76
- [x] ~~Improve Documentation~~ (separate global task)
- [x] #111
  - [x] Prettier Code formatting (especially tailwindcss)
- [x] #112
  - [x] [JSON-LD](https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data) for richer indexing
- [x] #113
  - https://www.zachleat.com/web/automatic-opengraph/
- [x] ~~Create Platform Specific Android or iOS Phone Preview on Landing Page~~
- [x] #114

**Comment by bemayr** [comment]
# Tasks

- [ ] Header (Navbar)
- [ ] Footer
- [ ] Landing Page
- [ ] App Page
- [ ] Metadata
- [ ] FAQs
- [ ] Categories
- [ ] Life Situations
- [ ] Im Notfall
