### ISSUE TITLE
[WIP]: Chatbot Integration

### ISSUE THREAD

**Issue by bemayr** [bemayr/young-carers-austria#6]
Instead of v1's search capabilities the newer version should support a chatbot (🤖) that enables users to search using a more personalized and text-based way of interacting.

This feature spans across the entire system with the need for message templates in the CMS, a new service to pick up those messages, combine them with the content and provide it via an API and plugins for iOS, Android and the Website to interact with the Chatbot. The chatbot should mimic some kind of human behavior (short random delay for messages, typing indicator, differentiating emojis (e.g. 🤖🧑🧔🏻🧑🏼‍🦰🧑🏽‍🦱🧑🏾‍🦳🧑🏿‍🦲)

This ideation issue should serve as the discussion and lookup for decisions taken around the chatbot.

## Phases
The implementation is planned in three steps. Those do not target the platforms, but the functionality of the chatbot.

### Phase 1
In the first phase the content for the chatbot is rather static and the chatbot simply does a keyword recognition which matches against predefined keywords set manually in the content management system.

### Phase 2
In the next phase the 

### CMS
It must be possible to change or add phrases for the chatbot in the content management system. At first we need alternating sentences for the following categories
1. Welcome Message
2. Results Found
3. No Results Found

### Chatbot Service
To improve personalisation, we will randomly select a name for the chatbot in the current session based on a list of around 60 names with a proper gender distribution. For this we could use: https://www.statistik.at/statistiken/bevoelkerung-und-soziales/bevoelkerung/geburten/vornamen-der-geborenen

### Website
A starting point for the website integration might be https://codepen.io/ScottWindon/pen/yLVgZjp.

**Comment by bemayr** [comment]
Did some research on possible implementations and found the following references to read:
- [ ] https://lucenenet.apache.org/index.html
- [ ] https://stackoverflow.com/questions/10971261/languages-supported-by-lucene-net
- [ ] https://insights.daffodilsw.com/blog/6-types-of-chatbots-know-which-one-works-best-for-your-business
- [ ] https://heartbeat.comet.ml/building-a-conversational-chatbot-with-nltk-and-tensorflow-part-1-f452ce1756e5

**Comment by bemayr** [comment]
Closing this because most of it is already implemented, while #109 tracks the remaining tasks.
